version: "3.9"

services:
  rnm:
    build: .
    image: rename:${TAG}
    container_name: renamet
    network_mode: bridge
    pull_policy: never

networks:
  default: 
    external: true
    name: bridge
